//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteImages.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
